---
- name: Configure ssh_config file
  hosts: all
  gather_facts: true

  tasks:

    - name: Configure SSH_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?Banner', line: 'Banner /etc/motd' }
        - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
        - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
      become: true

    - name: Restart SSHD service
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      become: true