---
- name: Configure vm.swappiness based on available RAM
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check the amount of RAM
      set_fact:
        memory_mb: "{{ ansible_facts['memtotal_mb'] }}"

    - name: Debug memory_mb variable
      debug:
        var: memory_mb

    - name: Set vm.swappiness to 10 if RAM > 2048MB
      ansible.builtin.sysctl:
        name: vm.swappiness
        value: 10
      when: memory_mb | int > 2048

    - name: Fail if RAM < 2048MB
      ansible.builtin.fail:
        msg: "Server memory less than 2048MB"
      when: memory_mb | int <= 2048


