---
- name: Create a custom fact for MySQL servers
  hosts: database
  become: true

  tasks:
    - name: Ensure the /etc/ansible/facts.d directory exists
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Set custom fact server_role=mysql
      ansible.builtin.copy:
        dest: /etc/ansible/facts.d/custom.fact
        content: |
          [custom]
          server_role=mysql
        mode: '0644'
        owner: root
        group: root

    - name: Gather facts again to include the custom fact
      ansible.builtin.setup:

    - name: Verify the custom fact
      ansible.builtin.debug:
        msg: "The server_role is set to: {{ ansible_facts['ansible_local']['custom'] }}"
